// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2wIVYn61Q-DvhbDr6RfXzC1MlNHCJPWU',
    appId: '1:42241232401:web:5273c1186d3200494febb0',
    messagingSenderId: '42241232401',
    projectId: 'reddit-clone-c0401',
    authDomain: 'reddit-clone-c0401.firebaseapp.com',
    storageBucket: 'reddit-clone-c0401.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqL26rJ21O-FWWsz0KAxuG8qsmkVsHeGw',
    appId: '1:42241232401:android:64ba3c05f2b84e5c4febb0',
    messagingSenderId: '42241232401',
    projectId: 'reddit-clone-c0401',
    storageBucket: 'reddit-clone-c0401.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOvcdatOCM5t7kW2UFL4yMDtsblKSgtOU',
    appId: '1:42241232401:ios:07e0ceca236b43334febb0',
    messagingSenderId: '42241232401',
    projectId: 'reddit-clone-c0401',
    storageBucket: 'reddit-clone-c0401.appspot.com',
    iosClientId: '42241232401-c3a0lrr6phk7223ataepgen64vmtm223.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );
}
